### ISSUE TITLE
This URL cannot be resolved by the github resolver?

### ISSUE THREAD

**Issue by StefH** [alincode/solc-resolver#1]
`https://github.com/mstack/bootcamp-blockchain-smartcontracts/Lab%204%20(SupplyChainLog)/Solidity/contracts/OrderContract.sol`

?

**Comment by alincode** [comment]
yes, it can.

![螢幕快照 2019-05-11 上午8 45 00](https://user-images.githubusercontent.com/7610755/57562959-afb56700-73ca-11e9-93b6-cc88087c37b6.png)
